apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mysql
          image: mariadb
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
              name: mysql
