apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
