apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: NodePort
  selector:
    app: vsftpd
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
      nodePort: 21
      name: ftp-control
    - protocol: TCP
      port: 2121
      targetPort: 2121
      nodePort: 2121
      name: ftp-data
