apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: vsftpd
spec:
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
        - name: ftps
          image: vsftpd-server
          imagePullPolicy: Never
          ports:
            - containerPort: 21
              name: ftp-control
            - containerPort: 2121
              name: ftp-data
