apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vsftpd
  name: vsftpd-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: vsftpd
spec:
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
        - name: ftps
          image: vsftpd
          imagePullPolicy: Never
          ports:
            - containerPort: 21
              name: ftp-control
            - containerPort: 2121
              name: ftp-data
          volumeMounts:
          - mountPath: /ftp_root
            name: ftp-root
      volumes:
      - name: ftp-root
        persistentVolumeClaim:
          claimName: vsftpd-storage
